[package]
name = "cli_prompts_rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
supports-unicode = "2.0.0"
console = "0.15.7"
colored = "2.0.4"